### ISSUE TITLE
download support m4a file

### ISSUE THREAD

**Issue by fabriguzden** [eviabs/Downtify#2]
you could make this application to be m4a and not mp3, I've already searched for downloaders with m4a compatibility and there's no :(
apologies for asking a lot

**Comment by eviabs** [comment]
You can either convert the created mp3 file to an m4a or convert the raw wav file to an m4a.

In `Recorder.cs` look for the function `public void ConvertToMP3()`
Inside the `try` statement, there are 3 lines that convert the raw wav file to an mp3:
```csharp
using (var reader = new AudioFileReader(_tempWavFilePath))
using (var writer = new LameMP3FileWriter(_mp3FilePath, reader.WaveFormat, _mp3Preset))   
   reader.CopyTo(writer);
```

Just replace them with your prefered converters.

Unfortunately, I'm not familiar with m4a format :(

**Comment by fabriguzden** [comment]
I was seeing that in chrome development tools, that spotify generates an unformatted file, but internally it is AAC 256kbps that is being an m4a file but it is encrypted
because you do not get familiar with aac .m4a, aac .m4a has more quality than an mp3 @eviabs 
of course, using libspotify since there is no other way
raw wav to m4a If so, could you do it?
I have not found any app capable of getting m4a from spotify, you would be my last hope

**Comment by eviabs** [comment]
Then you will have to convert the downloaded mp3 files to m4a files using any audio converter software.

**Comment by fabriguzden** [comment]
wav to m4a :+1: 
mp3 to m4a :-1: with convert mp3 to m4a aac, the quality will be equal to mp3
m4a aac is superior to mp3
Are you lazy to support m4a to Downtify? @eviabs

**Comment by fabriguzden** [comment]
@eviabs where is this name LameMP3FileWriter replaced by the name of some dll or ffmpeg exe to convert wav to m4a
